-- MySQL Script generated by MySQL Workbench
-- Mon May 15 01:14:10 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hotelsupport
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotelsupport
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotelsupport` DEFAULT CHARACTER SET latin1 ;
USE `hotelsupport` ;

-- -----------------------------------------------------
-- Table `hotelsupport`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelsupport`.`user` (
  `U_id` INT(10) NOT NULL,
  `U_company_name` VARCHAR(40) NOT NULL,
  `U_username` VARCHAR(20) NOT NULL,
  `U_password` VARCHAR(20) NOT NULL,
  `U_type` VARCHAR(20) NOT NULL,
  `U_email` VARCHAR(20) NOT NULL,
  `U_address` VARCHAR(150) NOT NULL,
  `U_language` VARCHAR(25) NOT NULL,
  `U_tell` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`U_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hotelsupport`.`order1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelsupport`.`order1` (
  `O_id` INT(10) NOT NULL,
  `O_order_number` INT(10) NOT NULL,
  `U_id_hotel` INT(10) NOT NULL,
  `U_id_supply` INT(10) NOT NULL,
  `P_id` INT(10) NOT NULL,
  `P_name` INT(25) NOT NULL,
  `P_price` INT(10) NOT NULL,
  `O_amount` INT(10) NOT NULL,
  `P_fee` VARCHAR(10) NOT NULL,
  `O_date` DATE NOT NULL,
  `O_price_total` INT(10) NOT NULL,
  `O_status` INT(15) NOT NULL,
  `user_U_id` INT(10) NOT NULL,
  PRIMARY KEY (`O_id`),
  INDEX `U_id_hotel` (`U_id_hotel` ASC),
  INDEX `U_id_supply` (`U_id_supply` ASC),
  INDEX `P_id` (`P_id` ASC),
  UNIQUE INDEX `O_id_UNIQUE` (`O_id` ASC),
  INDEX `fk_order1_user_idx` (`user_U_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hotelsupport`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelsupport`.`product` (
  `P_id` INT(20) NOT NULL,
  `P_name` VARCHAR(20) NOT NULL,
  `P_catagories` VARCHAR(20) NOT NULL,
  `P_grade` VARCHAR(5) NOT NULL,
  `P_price` INT(10) NOT NULL,
  `P_detail` VARCHAR(200) NOT NULL,
  `P_time_to_shipment` VARCHAR(5) NOT NULL,
  `P_fee` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`P_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hotelsupport`.`order_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelsupport`.`order_detail` (
  `order1_O_id` INT(10) NOT NULL,
  `product_P_id` INT(20) NOT NULL,
  `O_order_number` INT(10) NOT NULL,
  `P_name` VARCHAR(20) NOT NULL,
  `P_grade` VARCHAR(5) NOT NULL,
  `P_price` INT(10) NOT NULL,
  `O_amount` INT(10) NOT NULL,
  `O_price_total` INT(10) NOT NULL,
  `O_date` VARCHAR(10) NOT NULL,
  `order_detail_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`order1_O_id`, `product_P_id`, `order_detail_id`),
  INDEX `fk_order1_has_product_product1_idx` (`product_P_id` ASC),
  INDEX `fk_order1_has_product_order11_idx` (`order1_O_id` ASC),
  UNIQUE INDEX `order_detail_id_UNIQUE` (`order_detail_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
